from typing import Any, Sequence,List, overload
from ctypes import c_uint

def init_imgui() -> None: ...
def destroy_context() -> None: ...
def new_frame() -> None: ...
def render() -> None: ...
def shutdown() -> None: ...

def begin(name: str) -> None: ...
def end() -> None: ...
def text(content: str) -> None: ...
def show_demo_window(show: bool = True) -> None: ...
def dock_space() -> None: ...
def collapsing_header(label: str, visible: bool = True) -> bool: ...
def separator_text(text: str) -> None: ...
def checkbox(label: str, value: bool) -> bool: ...
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = "%.3f") -> float: ...
def slider_float2(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float]: ...
def slider_float3(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float, float]: ...
def slider_float4(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float, float, float]: ...

def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = "%d") -> int: ...
def slider_int2(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int]: ...
def slider_int3(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int, int]: ...
def slider_int4(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int, int, int]: ...

def input_text(label: str, text: str, flags: int = 0) -> str: ...
def input_float(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.3f") -> float: ...
def input_int(label: str, v: int, step: int = 1, step_fast: int = 100) -> int: ...
def input_float2(label: str, values: Sequence[float], format: str = "%.3f") -> tuple[float, float]: ...
def input_int2(label: str, values: Sequence[int]) -> tuple[int, int]: ...
def begin_child(str_id: str) -> bool: ...
def end_child() -> None: ...
def image(texture_id: int, size: tuple[float, float],
          uv0: tuple[float, float] = (0.0, 1.0),
          uv1: tuple[float, float] = (1.0, 0.0)) -> None: ...
def draw_imgui_info_widget() -> None: ...


class Turtle:
    def __init__(self, x: float = 0.0, y: float = 0.0, angle: float = 0.0) -> None: ...

    # Mouvement
    def forward(self, distance: float) -> None: ...
    def backward(self, distance: float) -> None: ...
    def right(self, angle: float) -> None: ...
    def left(self, angle: float) -> None: ...
    def goto(self, x: float, y: float,draw:bool = True) -> None: ...

    # Contrôle du stylo
    def penup(self) -> None: ...
    def pendown(self) -> None: ...
    def up(self) -> None: ...
    def down(self) -> None: ...

    # Propriétés
    @property
    def x(self) -> float: ...
    """read only"""
    @property
    def y(self) -> float: ...
    """read only"""
    @property
    def angle(self) -> float: ...
    """read only"""
    @property
    def pen_down(self) -> bool: ...
    """read only"""
    @property
    def show_turtle(self) -> bool: ...
    @show_turtle.setter
    def show_turtle(self, value: bool) -> None: ...
    @property
    def turtle_size(self) -> float: ...
    @turtle_size.setter
    def turtle_size(self, value: float) -> None: ...

    # Données vertex
    def get_vertices(self) -> List[float]: ...
    def get_vertex_count(self) -> int: ...
    @property
    def path_count(self) -> c_uint: ...
    @property
    def path_count_visible(self) -> c_uint: ...

    # Singleton
    @staticmethod
    def get_turtle() -> "Turtle": ...
    """Renvoie l’instance unique de Turtle (pattern singleton)."""


class TurtleRenderer:
    def __init__(self) -> None: ...
    def render(self) -> None: ...
    def cleanup(self) -> None: ...

    def set_camera(self, x: float, y: float, zoom: float) -> None: ...
    """Définit la position et le zoom de la caméra."""

    @staticmethod
    def initialize_glad() -> None: ...
    """Initialise Glad (à appeler une seule fois avant d’utiliser OpenGL)."""

    @staticmethod
    def get_size_chunk() -> int: ...


def create_turtle() -> Turtle: ...
"""Crée et retourne la tortue unique (singleton)."""

def get_turtle() -> Turtle: ...
"""Renvoie l’instance unique de Turtle."""

def initialize_glad() -> None: ...
"""Initialise Glad si ce n’est pas déjà fait."""