from typing import Any, Sequence, List, overload, Callable
from ctypes import c_uint

def open_popup(name:str) -> None: ...
def button(name:str) -> bool: ...
def get_selected_fractales_id() -> str: ...
def set_selected_fractales_id(id:str) -> None: ...
def render_menu_bar() -> None: ...
def get_fbo() -> int: ...
def render_dock_space() -> None: ...
def get_profondeur() -> int: ...
def on_resize(w:int,h:int) -> None: ...
def setShowProgress(s:bool) -> None: ...
def renderProgressBar() -> None: ...
def set_explorer_clicked_callback(callback:Callable[[int,int],None]) -> None: ...
def render_texture_information() -> None: ...

def begin_shader_preview() -> None: ...
def end_shader_preview() -> None: ...
def begin_render_shader_to_fbo() -> None: ...
def end_render_shader_to_fbo() -> None: ...
def init_fbo(w:int,h:int) -> None: ...
def get_fbo_screen_pos() -> tuple[float,float]: ...
def get_fbo_screen_size() -> tuple[float,float]: ...
def get_frame_size() -> tuple[int,int]: ...
def get_menu_bar_height() -> float: ...

def init_imgui() -> None: ...
def destroy_context() -> None: ...
def new_frame() -> None: ...
def render() -> None: ...
def shutdown() -> None: ...

def begin(name: str) -> None: ...
def end() -> None: ...
def text(content: str) -> None: ...
def show_demo_window(show: bool = True) -> None: ...
def dock_space() -> None: ...
def collapsing_header(label: str, visible: bool = True) -> bool: ...
def separator_text(text: str) -> None: ...
def checkbox(label: str, value: bool) -> bool: ...
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = "%.3f") -> float: ...
def slider_float2(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float]: ...
def slider_float3(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float, float]: ...
def slider_float4(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float, float, float]: ...

def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = "%d") -> int: ...
def slider_int2(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int]: ...
def slider_int3(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int, int]: ...
def slider_int4(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int, int, int]: ...

def input_text(label: str, text: str, flags: int = 0) -> str: ...
def input_float(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.3f") -> float: ...
def input_int(label: str, v: int, step: int = 1, step_fast: int = 100) -> int: ...
def input_float2(label: str, values: Sequence[float], format: str = "%.3f") -> tuple[float, float]: ...
def input_int2(label: str, values: Sequence[int]) -> tuple[int, int]: ...
def begin_child(str_id: str) -> bool: ...
def end_child() -> None: ...
def image(texture_id: int, size: tuple[float, float],
          uv0: tuple[float, float] = (0.0, 1.0),
          uv1: tuple[float, float] = (1.0, 0.0)) -> None: ...
def draw_imgui_info_widget() -> None: ...

def update_color_edit_timer(dt:float) -> None: ...

class Turtle:
    def __init__(self, x: float = 0.0, y: float = 0.0, angle: float = 0.0) -> None: ...

    # Mouvement
    def forward(self, distance: float) -> None: ...
    def backward(self, distance: float) -> None: ...
    def right(self, angle: float) -> None: ...
    def left(self, angle: float) -> None: ...
    def goto(self, x: float, y: float,draw:bool = True) -> None: ...

    # Contrôle du stylo
    def penup(self) -> None: ...
    def pendown(self) -> None: ...
    def up(self) -> None: ...
    def down(self) -> None: ...

    # Propriétés
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def angle(self) -> float: ...
    @angle.setter
    def angle(self,value:float) -> None: ...
    @property
    def pen_down(self) -> bool: ...
    @property
    def show_turtle(self) -> bool: ...
    @show_turtle.setter
    def show_turtle(self, value: bool) -> None: ...
    @property
    def turtle_size(self) -> float: ...
    @turtle_size.setter
    def turtle_size(self, value: float) -> None: ...

    # Données vertex
    def get_vertices(self) -> List[float]: ...
    def get_vertex_count(self) -> int: ...
    @property
    def path_count(self) -> c_uint: ...
    @property
    def path_count_visible(self) -> c_uint: ...

    # Singleton
    @staticmethod
    def get_turtle() -> "Turtle": ...
    """Renvoie l’instance unique de Turtle (pattern singleton)."""

    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def can_undo(self) -> bool: ...
    def can_redo(self) -> bool: ...
    def clear_undo_history(self) -> None: ...
    def set_undo_limit(self,limit) -> None: ...
    def get_memory_redo(self) -> int: ...
    def get_memory_undo(self) -> int: ...
    def get_size_redo(self) -> None: ...
    def get_size_undo(self) -> None: ...
    def save_state_for_undo(self) -> None: ...
    def set_color(self,x:int,y:int,z:int): ...
    def get_color(self) -> tuple[int, int, int]: ...


class TurtleRenderer:
    def __init__(self,fPath:str,vPath:str) -> None: ...
    def render(self) -> None: ...
    def cleanup(self) -> None: ...

    def set_camera(self, x: float, y: float, zoom: float) -> None: ...
    """Définit la position et le zoom de la caméra."""

    @staticmethod
    def initialize_glad() -> None: ...
    """Initialise Glad (à appeler une seule fois avant d’utiliser OpenGL)."""

    @staticmethod
    def get_size_chunk() -> int: ...

def save_fbo_to_file(name:str) -> None: ...
def open_preview_screenshot() -> None: ...
def render_preview_screenshot() -> None: ...
def get_angle() -> float: ...
def create_turtle() -> Turtle: ...
"""Crée et retourne la tortue unique (singleton)."""

def get_turtle() -> Turtle: ...
"""Renvoie l’instance unique de Turtle."""

def initialize_glad() -> None: ...
"""Initialise Glad si ce n’est pas déjà fait."""

def ajouter_fractale(id:str,name:str,path:str) -> None: ...