from typing import Any, Sequence

def init_imgui() -> None: ...
def destroy_context() -> None: ...
def new_frame() -> None: ...
def render() -> None: ...
def shutdown() -> None: ...

def begin(name: str) -> None: ...
def end() -> None: ...
def text(content: str) -> None: ...
def show_demo_window(show: bool = True) -> None: ...
def dock_space() -> None: ...
def collapsing_header(label: str, visible: bool = True) -> bool: ...
def separator_text(text: str) -> None: ...
def checkbox(label: str, value: bool) -> bool: ...
def slider_float(label: str, v: float, v_min: float, v_max: float, format: str = "%.3f") -> float: ...
def slider_float2(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float]: ...
def slider_float3(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float, float]: ...
def slider_float4(label: str, values: Sequence[float], v_min: float, v_max: float, format: str = "%.3f") -> tuple[float, float, float, float]: ...

def slider_int(label: str, v: int, v_min: int, v_max: int, format: str = "%d") -> int: ...
def slider_int2(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int]: ...
def slider_int3(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int, int]: ...
def slider_int4(label: str, values: Sequence[int], v_min: int, v_max: int, format: str = "%d") -> tuple[int, int, int, int]: ...

def input_text(label: str, text: str, flags: int = 0) -> str: ...
def input_float(label: str, v: float, step: float = 0.0, step_fast: float = 0.0, format: str = "%.3f") -> float: ...
def input_int(label: str, v: int, step: int = 1, step_fast: int = 100) -> int: ...
def input_float2(label: str, values: Sequence[float], format: str = "%.3f") -> tuple[float, float]: ...
def input_int2(label: str, values: Sequence[int]) -> tuple[int, int]: ...